In [1]:
from __future__ import print_function
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D
from keras.layers import LSTM
from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.text import hashing_trick
from keras.preprocessing.text import one_hot

from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D, MaxPooling1D

import sys
import pandas as pd
import numpy as np
import re
from sklearn import linear_model
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import svm

from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier



from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from sklearn.naive_bayes import GaussianNB

import nltk
from nltk import word_tokenize          
from nltk.stem.porter import PorterStemmer

from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MultiLabelBinarizer

from keras import metrics
from keras import losses



/home/nikepupu/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [15]:
t = pd.read_csv("./reports/data.csv")
t.dropna()



def check(a):
    if a in ['math','dp','implementation','geometry', 'greedy', 'combinatorics', 'datastructures'
            , 'games', 'graphs', 'numbertheory', 'probabilities', 'strings'] :
        return True
    else:
        return False
temp = t['labels'].tolist()
res = [text_to_word_sequence(a) for a in temp]
res = [[a for a in line if check(a) ] for line in res]
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(res)
y = y*100

In [16]:
vectorizer = TfidfVectorizer( stop_words="english",analyzer = 'word')
feature = "problem-statement"

l = t['ps'] = (t['problem-statement'].astype(str) + t['output-spec']) .tolist()
res = []
regex = re.compile("^a-zA-Z0-9\ '" )
def clean_s(input_str):
    return regex.sub(' ', input_str)

for i in range(len(l)):
    try:
        res.append(clean_s(l[i]))
    except:
        res.append("")

X = vectorizer.fit_transform(res)
t['tf-idf'] = list(X.toarray())
x_train, x_test, y_train, y_test = train_test_split(X.todense(),y, test_size=0.2,random_state=42)
print(X.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
from skmultilearn.problem_transform import BinaryRelevance
from skmultilearn.problem_transform import ClassifierChain
from skmultilearn.problem_transform import LabelPowerset
from skmultilearn.adapt import MLkNN
model = BinaryRelevance(linear_model.LogisticRegression())

#model = MLkNN(k=10)
#model = LabelPowerset(GaussianNB())
model.fit(x_train, y_train)

KeyboardInterrupt: 

In [ ]:
y_pred = model.predict(x_test)
print(classification_report(y_test, y_pred))